INSERT INTO AMBASSADOR (NAME, DESCRIPTION) VALUES ('Ambassador 1', 'An Ambassador 1');
INSERT INTO AMBASSADOR (NAME, DESCRIPTION) VALUES ('Ambassador 2', 'An Ambassador 2');

INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Afrikaans');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Albanian');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Amharic');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Arabic - Algeria');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Arabic - Bahrain');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Arabic - Egypt');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Arabic - Iraq');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Arabic - Jordan');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Arabic - Kuwait');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Arabic - Lebanon');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Arabic - Libya');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Arabic - Morocco');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Arabic - Oman');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Arabic - Qatar');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Arabic - Saudi Arabia');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Arabic - Syria');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Arabic - Tunisia');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Arabic - United Arab Emirates');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Arabic - Yemen');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Armenian');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Assamese');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Azeri - Cyrillic');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Azeri - Latin');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Basque');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Belarusian');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Bengali - Bangladesh');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Bengali - India');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Bosnian');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Bulgarian');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Burmese');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Catalan');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Chinese - China');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Chinese - Hong Kong SAR');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Chinese - Macau SAR');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Chinese - Singapore');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Chinese - Taiwan');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Croatian');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Czech');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Danish');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Divehi');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Dutch - Belgium');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Dutch - Netherlands');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Edo');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'English - Australia');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'English - Belize');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'English - Canada');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'English - Caribbean');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'English - Great Britain');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'English - India');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'English - Ireland');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'English - Jamaica');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'English - New Zealand');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'English - Phillippines');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'English - Southern Africa');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'English - Trinidad');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'English - United States');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'English - Zimbabwe');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Estonian');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'FYRO Macedonia');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Faroese');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Farsi - Persian');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Filipino');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Finnish');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'French - Belgium');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'French - Cameroon');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'French - Canada');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'French - Congo');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'French - France');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'French - Luxembourg');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'French - Mali');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'French - Monaco');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'French - Morocco');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'French - Senegal');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'French - Switzerland');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'French - West Indies');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Frisian - Netherlands');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Gaelic - Ireland');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Gaelic - Scotland');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Galician');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Georgian');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'German - Austria');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'German - Germany');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'German - Liechtenstein');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'German - Luxembourg');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'German - Switzerland');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Greek');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Guarani - Paraguay');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Gujarati');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'HID (Human Interface Device)');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Hebrew');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Hindi');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Hungarian');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Icelandic');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Igbo - Nigeria');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Indonesian');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Italian - Italy');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Italian - Switzerland');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Japanese');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Kannada');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Kashmiri');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Kazakh');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Khmer');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Konkani');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Korean');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Kyrgyz - Cyrillic');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Lao');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Latin');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Latvian');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Lithuanian');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Malay - Brunei');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Malay - Malaysia');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Malayalam');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Maltese');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Manipuri');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Maori');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Marathi');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Mongolian');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Mongolian');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Nepali');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Norwegian - Bokml');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Norwegian - Nynorsk');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Oriya');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Polish');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Portuguese - Brazil');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Portuguese - Portugal');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Punjabi');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Raeto-Romance');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Romanian - Moldova');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Romanian - Romania');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Russian');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Russian - Moldova');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Sami Lappish');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Sanskrit');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Serbian - Cyrillic');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Serbian - Latin');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Sesotho (Sutu)');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Setsuana');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Sindhi');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Sinhala');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Slovak');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Slovenian');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Somali');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Sorbian');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Spanish - Argentina');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Spanish - Bolivia');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Spanish - Chile');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Spanish - Colombia');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Spanish - Costa Rica');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Spanish - Dominican Republic');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Spanish - Ecuador');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Spanish - El Salvador');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Spanish - Guatemala');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Spanish - Honduras');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Spanish - Mexico');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Spanish - Nicaragua');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Spanish - Panama');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Spanish - Paraguay');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Spanish - Peru');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Spanish - Puerto Rico');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Spanish - Spain (Traditional)');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Spanish - Uruguay');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Spanish - Venezuela');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Swahili');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Swedish - Finland');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Swedish - Sweden');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Syriac');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Tajik');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Tamil');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Tatar');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Telugu');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Thai');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Tibetan');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Tsonga');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Turkish');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Turkmen');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Ukrainian');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Unicode');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Urdu');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Uzbek - Cyrillic');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Uzbek - Latin');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Venda');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Vietnamese');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Welsh');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Xhosa');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Yiddish');
INSERT INTO tag (TYPE, NAME) VALUES ('Language', 'Zulu');
